class SystemConfig:
    # --- COMMUNICATIONS ---
    # PASTE DISCORD WEBHOOK URL BELOW TO ENABLE PHONE ALERTS
    DISCORD_WEBHOOK_URL = "" 
    
    # --- STRATEGY SETTINGS ---
    VOLATILITY_LOOKBACK = 14
    BASE_Z_ENTRY = -1.5
    BASE_RSI_ENTRY = 35
    
    # --- RISK MANAGEMENT ---
    MAX_KELLY_FRACTION = 0.5   
    MAX_CAPITAL_USAGE  = 0.25  
    MAX_DAILY_DRAWDOWN = -0.03 
    
    # --- REALITY SIMULATION ---
    SIMULATE_SLIPPAGE = 0.001 
    SIMULATE_FEES     = 1.00